"""Cases for ``generate_fixtures.py``: common primitives, compared as exact unitaries.

Case ids double as fixture names.
"""

from typing import Any, Dict, List

CASES: List[Dict[str, Any]] = [
    {"id": "empty_n3", "component": "empty", "n": 3},
    {"id": "state_setter_4_6", "component": "state_setter", "n": 4, "state": 6},
    {"id": "state_setter_3_0", "component": "state_setter", "n": 3, "state": 0},
    {
        "id": "mcswap_5_01_23",
        "component": "mcswap",
        "n": 5,
        "controls": [0, 1],
        "targets": (2, 3),
    },
    {
        "id": "mcswap_5_02_41",
        "component": "mcswap",
        "n": 5,
        "controls": [0, 2],
        "targets": (4, 1),
    },
    {
        "id": "mcswap_4_3_02",
        "component": "mcswap",
        "n": 4,
        "controls": [3],
        "targets": (0, 2),
    },
    {"id": "hwadder_2_3", "component": "hwadder", "x": 2, "y": 3},
    {"id": "hwadder_3_2", "component": "hwadder", "x": 3, "y": 2},
    {"id": "hwadder_1_4", "component": "hwadder", "x": 1, "y": 4},
    {"id": "tqft_3_5", "component": "truncated_qft", "n": 3, "dft_size": 5},
    {"id": "tqft_2_3", "component": "truncated_qft", "n": 2, "dft_size": 3},
    {"id": "tqft_4_6", "component": "truncated_qft", "n": 4, "dft_size": 6},
    {
        "id": "usp_3_5_0",
        "component": "uniform_state_prep",
        "n": 3,
        "states": 5,
        "ctrl": 0,
    },
    {
        "id": "usp_3_6_0",
        "component": "uniform_state_prep",
        "n": 3,
        "states": 6,
        "ctrl": 0,
    },
    {
        "id": "usp_2_4_0",
        "component": "uniform_state_prep",
        "n": 2,
        "states": 4,
        "ctrl": 0,
    },
    {
        "id": "usp_3_5_2",
        "component": "uniform_state_prep",
        "n": 3,
        "states": 5,
        "ctrl": 2,
    },
    {
        "id": "usp_3_1_0",
        "component": "uniform_state_prep",
        "n": 3,
        "states": 1,
        "ctrl": 0,
    },
    {
        "id": "usp_4_12_1",
        "component": "uniform_state_prep",
        "n": 4,
        "states": 12,
        "ctrl": 1,
    },
    {"id": "pshift_4_pos", "component": "phase_shift", "n": 4, "positive": True},
    {"id": "pshift_4_neg", "component": "phase_shift", "n": 4, "positive": False},
    {"id": "pshift_3_pos", "component": "phase_shift", "n": 3, "positive": True},
    {
        "id": "ppshift_4_3_pos_0",
        "component": "param_phase_shift",
        "n": 4,
        "add": 3,
        "positive": True,
        "ctrl": 0,
    },
    {
        "id": "ppshift_4_5_neg_2",
        "component": "param_phase_shift",
        "n": 4,
        "add": 5,
        "positive": False,
        "ctrl": 2,
    },
    {
        "id": "ppshift_3_1_pos_1",
        "component": "param_phase_shift",
        "n": 3,
        "add": 1,
        "positive": True,
        "ctrl": 1,
    },
    {
        "id": "draper_3_2_pos_0",
        "component": "draper_adder",
        "n": 3,
        "add": 2,
        "positive": True,
        "ctrl": 0,
    },
    {
        "id": "draper_3_1_neg_1",
        "component": "draper_adder",
        "n": 3,
        "add": 1,
        "positive": False,
        "ctrl": 1,
    },
    {
        "id": "draper_4_5_pos_2",
        "component": "draper_adder",
        "n": 4,
        "add": 5,
        "positive": True,
        "ctrl": 2,
    },
    {
        "id": "addconv_3_2_6_0",
        "component": "addition_conversion",
        "n": 3,
        "state_from": 2,
        "state_to": 6,
        "ctrl": 0,
    },
    {
        "id": "addconv_3_1_5_1",
        "component": "addition_conversion",
        "n": 3,
        "state_from": 1,
        "state_to": 5,
        "ctrl": 1,
    },
    {
        "id": "addconv_2_0_3_0",
        "component": "addition_conversion",
        "n": 2,
        "state_from": 0,
        "state_to": 3,
        "ctrl": 0,
    },
    {"id": "trcomp_2_lt", "component": "two_register_comparator", "n": 2, "mode": "LT"},
    {"id": "trcomp_2_le", "component": "two_register_comparator", "n": 2, "mode": "LE"},
    {"id": "trcomp_2_ge", "component": "two_register_comparator", "n": 2, "mode": "GE"},
    {"id": "trcomp_1_gt", "component": "two_register_comparator", "n": 1, "mode": "GT"},
    {
        "id": "srcomp_3_2_lt",
        "component": "single_register_comparator",
        "n": 3,
        "num": 2,
        "mode": "LT",
    },
    # num == 2**(n-1) - 1: GT special case (identity circuit)
    {
        "id": "srcomp_3_3_gt",
        "component": "single_register_comparator",
        "n": 3,
        "num": 3,
        "mode": "GT",
    },
    # num == 2**(n-1) - 1: LE special case (wraps to GE against 0)
    {
        "id": "srcomp_3_3_le",
        "component": "single_register_comparator",
        "n": 3,
        "num": 3,
        "mode": "LE",
    },
    {
        "id": "srcomp_4_5_ge",
        "component": "single_register_comparator",
        "n": 4,
        "num": 5,
        "mode": "GE",
    },
    {
        "id": "srcomp_3_1_gt",
        "component": "single_register_comparator",
        "n": 3,
        "num": 1,
        "mode": "GT",
    },
    # equivalence classes are selected by their id() == (mass, momentum)
    {
        "id": "eqcperm_d1q3_fwd",
        "component": "eqc_permutation",
        "discretization": "D1Q3",
        "eqc_mass": 2,
        "eqc_momentum": [0],
        "inverse": False,
    },
    {
        "id": "eqcperm_d2q4_fwd",
        "component": "eqc_permutation",
        "discretization": "D2Q4",
        "eqc_mass": 2,
        "eqc_momentum": [0, 0],
        "inverse": False,
    },
    {
        "id": "eqcperm_d2q4_inv",
        "component": "eqc_permutation",
        "discretization": "D2Q4",
        "eqc_mass": 2,
        "eqc_momentum": [0, 0],
        "inverse": True,
    },
    {
        "id": "eqcperm_d3q6_m2_fwd",
        "component": "eqc_permutation",
        "discretization": "D3Q6",
        "eqc_mass": 2,
        "eqc_momentum": [0, 0, 0],
        "inverse": False,
    },
    {
        "id": "eqcperm_d3q6_m4_inv",
        "component": "eqc_permutation",
        "discretization": "D3Q6",
        "eqc_mass": 4,
        "eqc_momentum": [0, 0, 0],
        "inverse": True,
    },
    {
        "id": "eqcperm_d3q6_m3px_inv",
        "component": "eqc_permutation",
        "discretization": "D3Q6",
        "eqc_mass": 3,
        "eqc_momentum": [1, 0, 0],
        "inverse": True,
    },
    # size-2 classes exercise the controlled-ry path
    {
        "id": "eqcredist_d1q3",
        "component": "eqc_redistribution",
        "discretization": "D1Q3",
        "eqc_mass": 2,
        "eqc_momentum": [0],
        "decompose": True,
    },
    {
        "id": "eqcredist_d2q4",
        "component": "eqc_redistribution",
        "discretization": "D2Q4",
        "eqc_mass": 2,
        "eqc_momentum": [0, 0],
        "decompose": True,
    },
    {
        "id": "eqcredist_d3q6_m3py",
        "component": "eqc_redistribution",
        "discretization": "D3Q6",
        "eqc_mass": 3,
        "eqc_momentum": [0, 1, 0],
        "decompose": True,
    },
    # size-3 classes exercise the controlled truncated-DFT path
    {
        "id": "eqcredist_d3q6_m2",
        "component": "eqc_redistribution",
        "discretization": "D3Q6",
        "eqc_mass": 2,
        "eqc_momentum": [0, 0, 0],
        "decompose": True,
    },
    {
        "id": "eqcredist_d3q6_m4",
        "component": "eqc_redistribution",
        "discretization": "D3Q6",
        "eqc_mass": 4,
        "eqc_momentum": [0, 0, 0],
        "decompose": False,
    },
    {"id": "eqccoll_d1q3", "component": "eqc_collision", "discretization": "D1Q3"},
    {"id": "eqccoll_d2q4", "component": "eqc_collision", "discretization": "D2Q4"},
    {"id": "eqccoll_d3q6", "component": "eqc_collision", "discretization": "D3Q6"},
]
